#
# Copyright (C) 2020-2022 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
authors = ["Signal Messenger LLC"]
edition = "2018"
license = "AGPL-3.0-only"
name = "libsignal-protocol"
version = "0.1.0"

[dependencies]
aes = {version = "0.7.4", features = ["ctr"]}
aes-gcm-siv = "0.10.1"
arrayref = "0.3.6"
async-trait = "0.1.41"
block-modes = "0.8"
curve25519-dalek = "3.0"
displaydoc = "0.2"
hex = "0.4"
hkdf = "0.11"
hmac = "0.11.0"
itertools = "0.10.1"
log = "0.4"
num_enum = "0.5.1"
prost = "0.9"
rand = "0.7.3"
serde = {version = "1.0.147", optional = true}
sha2 = "0.9"
subtle = "2.2.3"
thiserror = "1.0.30"
uuid = "1.1.2"
x25519-dalek = "1.0"

[features]
armv8 = ["aes/armv8", "aes-gcm-siv/armv8"]
serde = ["dep:serde"]

[dev-dependencies]
criterion = "0.4"
futures-util = "0.3.7"

[build-dependencies]
prost-build = "0.9"

[[bench]]
harness = false
name = "session"

[[bench]]
harness = false
name = "ratchet"

[[bench]]
harness = false
name = "sealed_sender"
