[workspace]
members = [
    "rust/aes-gcm-siv",
    "rust/device-transfer",
    "rust/poksho",
    "rust/protocol",
    "rust/bridge/ffi",
    "rust/bridge/jni",
    "rust/bridge/node",
]
default-members = [
    "rust/aes-gcm-siv",
    "rust/device-transfer",
    "rust/poksho",
    "rust/protocol",
]

[patch.crates-io]
curve25519-dalek = { git = 'https://github.com/signalapp/curve25519-dalek', branch = '3.0.0-lizard2' }
