[package]
name = "device-transfer"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
boring = { version = "3.1.0", default-features = false }
libc = "0.2"

[dev-dependencies]
hex = "0.4"
