#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-ffi"
version = "0.45.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[lib]
name = "signal_ffi"
crate-type = ["staticlib"]

[features]
# Testing the Swift side of this requires compiling with SIGNAL_MEDIA_SUPPORTED enabled for both Swift and C:
#     swift test -Xswiftc -DSIGNAL_MEDIA_SUPPORTED -Xcc -DSIGNAL_MEDIA_SUPPORTED
signal-media = ["libsignal-bridge/signal-media"]
testing-fns = ["libsignal-bridge/testing-fns"]

[dependencies]
attest = { path = "../../attest" }
device-transfer = { path = "../../device-transfer" }
libsignal-bridge = { path = "../shared", features = ["ffi"] }
libsignal-net = { path = "../../net" }
libsignal-protocol = { path = "../../protocol" }
signal-crypto = { path = "../../crypto" }
signal-media = { path = "../../media" }
signal-pin = { path = "../../pin" }
usernames = { path = "../../usernames" }
zkgroup = { path = "../../zkgroup" }

async-trait = "0.1.41"
futures-util = "0.3"
log = { version = "0.4", features = ["release_max_level_info"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
rand = "0.8"

[target.aarch64-apple-ios.dependencies]
cpufeatures = "0.2.1" # Make sure iOS gets optimized crypto.
