#
# Copyright (C) 2023 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#
[package]
name = "libsignal-message-backup"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[dependencies]
libsignal-protocol = { path = "../protocol"}

aes = "0.8.3"
arrayvec = "0.7.4"
async-compression = { version = "0.4.5", features = ["futures-io", "gzip"] }
cbc = "0.1.2"
displaydoc = "0.2.4"
futures = "0.3.29"
hkdf = "0.12"
hmac = "0.12"
log = "0.4"
prost = "0.12"
sha2 = "0.10"
thiserror = "1.0.50"
derive-where = "1.2.5"
subtle = "2.5.0"

[dev-dependencies]
signal-crypto = { path = "../crypto" }

array-concat = "0.5.2"
assert_matches = "1.5.0"
futures = { version = "0.3.29", features = ["executor"] }
hex-literal = "0.4.1"
test-case = "3.3.1"
test-log = "0.2.14"

[build-dependencies]
prost-build = "0.12"
