#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
libsignal-protocol = { path = "../../protocol" }
libsignal-net = { path = "../../net" }
signal-crypto = { path = "../../crypto" }
device-transfer = { path = "../../device-transfer" }
attest = { path = "../../attest" }
zkgroup = { path = "../../zkgroup" }
usernames = { path = "../../usernames" }
signal-pin = { path = "../../pin" }
signal-media = { path = "../../media", optional = true }
libsignal-bridge-macros = { path = "macros" }
aes-gcm-siv = "0.11.1"
async-trait = "0.1.41"
bincode = "1.0"
futures-util = "0.3.7"
hkdf = "0.12"
hmac = "0.12.0"
log = "0.4"
partial-default = "0.1.0"
paste = "1.0"
rand = "0.8"
scopeguard = "1.0"
serde = "1.0"
serde_derive = { version = "1.0.180", features = ["deserialize_in_place"] }
sha2 = "0.10"
static_assertions = "1.1"
tokio = { version = "1" }
uuid = "1.1.2"

# Enable this for all libsignal app language libraries
subtle = { version = "2.5", features = ["core_hint_black_box"] }

bytemuck = { version = "1.13.0", optional = true }
jni = { version = "0.21", package = "jni", optional = true }
neon = { version = "0.10.0", optional = true, default-features = false, features = ["napi-6", "promise-api"] }
linkme = { version = "0.3.9", optional = true }
signal-neon-futures = { path = "../node/futures", optional = true }
num_enum = "0.6.1"
nonzero_ext = "0.3.0"

[features]
ffi = []
jni = ["dep:jni", "bytemuck"]
node = ["neon", "linkme", "signal-neon-futures"]
