#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-node"
version = "0.44.0"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "signal_node"
crate-type = ["cdylib"]

[dependencies]
libsignal-bridge = { path = "../shared", features = ["node", "signal-media"] }
libsignal-protocol = { path = "../../protocol" }
signal-neon-futures = { path = "futures" }

async-trait = "0.1.41"
futures = { version = "0.3", default-features = false, features = ["executor"] }
log = { version = "0.4", features = ["release_max_level_info"] }
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
minidump = { version = "0.20.0", default-features = false }
minidump-processor = { version = "0.20.0", default-features = false }
minidump-unwind = { version = "0.20.0", default-features = false }
neon = { version = "1.0.0", default-features = false, features = ["napi-6"] }
rand = "0.8"

[build-dependencies]
# cmake 0.1.49 breaks no-toolchain Windows cross-compilation using Visual Studio
# https://github.com/rust-lang/cmake-rs/pull/158#issuecomment-1544695163
cmake = ">= 0.1, < 0.1.49"

[features]
testing-fns = ["libsignal-bridge/testing-fns"]
