[package]
name = "signal-media"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
futures-util = "0.3.7"
mediasan-common = "0.5.0"
mp4san = { version = "0.5.0", optional = true }
thiserror = "1.0.38"
webpsan = { version = "0.5.0", optional = true, default_features = false }

[features]
default = ["mp4san", "webpsan"]
mp4san = ["dep:mp4san"]
webpsan = ["dep:webpsan"]
