name: Lints
# This is in a separate job because we have shell scripts scattered across all our targets,
# *and* some of them have common dependencies.

on:
  push:
    branches: [ main ]
    paths: ['**/*.sh', '**/*.py', '.github/workflows/lints.yml']
  pull_request:
    paths: ['**/*.sh', '**/*.py', '.github/workflows/lints.yml']

jobs:
  lint:
    name: Check helper scripts

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - run: pip3 install flake8 mypy
    - run: shellcheck **/*.sh bin/verify_duplicate_crates bin/adb-run-test
    - run: python3 -m flake8 .
    # Only include typed Python scripts here.
    - run: python3 -m mypy bin/fetch_archive.py --python-version 3.8 --strict
