name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag)'
        required: true
      npm_tag:
        description: 'NPM tag'
        required: true
        default: 'latest'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        include:
        - os: macos-11
          additional-rust-target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.additional-rust-target }}

    - name: Get Node version from .nvmrc
      id: get-nvm-version
      shell: bash
      run: echo "::set-output name=node-version::$(cat .nvmrc)"

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-nvm-version.outputs.node-version }}

    - name: Verify that the Node bindings are up to date
      run: rust/bridge/node/bin/gen_ts_decl.py --verify
      if: matrix.os == 'ubuntu-latest'

    - run: yarn install --ignore-scripts --frozen-lockfile
      working-directory: node

    - run: npx prebuildify --napi -t ${{ steps.get-nvm-version.outputs.node-version }} --arch arm64
      working-directory: node
      if: matrix.os == 'macos-11'

    - run: npx prebuildify --napi -t ${{ steps.get-nvm-version.outputs.node-version }}
      working-directory: node

    - name: Upload library
      uses: actions/upload-artifact@v2
      with:
        name: libsignal_client (${{matrix.os}})
        path: node/prebuilds/*

  publish:
    name: Publish

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Get Node version from .nvmrc
      id: get-nvm-version
      shell: bash
      run: echo "::set-output name=node-version::$(cat .nvmrc)"

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-nvm-version.outputs.node-version }}

    - name: Download built libraries
      id: download
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Copy libraries
      run: mkdir node/prebuilds && mv ${{ steps.download.outputs.download-path }}/*/* node/prebuilds && find node/prebuilds

    - run: yarn install --frozen-lockfile
      working-directory: node

    - run: yarn tsc
      working-directory: node

    - run: yarn lint
      working-directory: node

    - run: yarn format -c
      working-directory: node

    - name: Run yarn test
      uses: GabrielBB/xvfb-action@v1.4
      with:
        # The tests use an Electron-based runner, so we need to set up a dummy display for them.
        run: yarn test
        working-directory: node
      env:
        PREBUILDS_ONLY: 1

    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: ${{ github.event.inputs.npm_tag }}
        package: node/package.json
        access: "public"
